config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :posts do
      get 'user_profile'
    end
  end
  resources :projects do
    resources :tasks
  end
  resources :teams
  devise_for :users

  root 'home#index'

  get "/join/:id", to:"teams#user" ,as:"join"
  get "/view/:id", to:"teams#view_team", as:"view_team"
  delete "/exit/:id", to:"teams#team_exit", as:"exit_team"
  get "/analytics/:id", to:"home#analytics" ,as:"analytics"
  get "/notify_users", to: "tasks#notify_developers", as:"notify_developers"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  after_save :send_task_mail

  def send_task_mail
    TaskMailer.with(user: self.assigned_user, task: self).welcome_mail.deliver_now
  end

  def self.send_notification(dead_task)
    TaskMailer.with(user: dead_task.assigned_user, task: dead_task).time_exceed.deliver_now
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.build
    @teams = Team.includes(:users).all
    @users = []
    @teams.each do |team|
      team.users.each do |team_user|
        @users << team_user.email+"("+team.name+")"
      end
    end
  end

  # GET /tasks/1/edit
  def edit
    @teams = Team.includes(:users).all
    @users = []
    @teams.each do |team|
      team.users.each do |team_user|
        @users << team_user.email+"("+team.name+")"
      end
    end
  end



  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(@project), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_tasks_path(@project), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_tasks_path(@project), notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def notify_developers
    puts "Request Received with project ID #{params}"
    @project.tasks.all.each do |task|
      user = task.assigned_user.split('(')[0]
      if (task.updated_at + task.estimation.hour < Time.now.utc) and (current_user.email == user) and (task.status != 'COMPLETED')
        Task.send_notification(task)
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :estimation, :status, :assigned_user, :project_id)
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="container">
  <%= form_with(model:[@project,task]) do |form| %>
    <% if task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
          <% task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title, class: "label" %>
      <%= form.text_field :title, type: "input", class: "input", required: true %>
    </div>

    <div class="field">
      <%= form.label :description, class: "label" %>
      <%= form.text_area :description, class: "textarea", required: true %>
    </div>

    <div class="field">
      <%= form.label :Estimation_in_Hours, class: "label" %>
      <%= form.number_field :estimation, type: "input", class: "input", required: true %>
    </div>

    <div class="field">
      <%= form.label :status, class: "label" %>
      <%= form.radio_button :status,"IN PROGRESS" %> In Progess <br/>
      <%= form.radio_button :status,"YET TO START" %> Yet to Start <br/>
      <%= form.radio_button :status,"COMPLETED" %> Completed <br/>

    </div>

    <div class="field">
      <%= form.label :Choose_user_to_assign,class:"label" %>
      <%= form.select :assigned_user, @users, class:"input" %>
    </div>

    <div class="field">
      <%= form.text_field :project_id, type: "hidden" %>
    </div>

    <div class="actions columns">
      <div class="column">
        <%= form.submit :submit, class: "button is-link" %>
      </div>

      <div class="column">
        <%= link_to('Back', root_path, class: "button is-light redirect-link") %>
      </div>
    </div>
  <% end %>

</div>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<br>
<div class="container content" style="height: 35rem;">
  <div class="card" style="margin-top: 3rem;">
    <div class="columns is-multiline" style="justify-content: center; align-items: center;">
      <%= button_to("New Task", new_project_task_path(@project), class: "button", method: :get, style: "width: 15rem; background-color: #8080ff") %>
      <button class="button notify_developers" style="width: 15rem; background-color: orange">Notify</button>
    </div>
    <div class="table-responsive text-nowrap" style="height: 25rem; justify-content: center;">
      <table class="table" style="text-align: left;">
        <thead class="table-light">
        <tr>
          <th>Task Name</th>
          <th>Description</th>
          <th>Project</th>
          <th>Status</th>
          <th>Actions</th>
          <th>Delete</th>
        </tr>
        </thead>
        <tbody class="table-border-bottom-0">
        <% @tasks.each do |task| %>

          <tr style="justify-content: center;" >
            <td><strong> <%= task.title %> </strong></td>
            <td>Description</td>
            <td> <%= task.project.title %> </td>
            <td>
              <% if task.status.downcase == 'in progesss' %>
                <span class="badge bg-label-primary me-1"> <%= task.status %> </span>
              <% elsif task.status.downcase == 'completed' %>
                <span class="badge bg-label-success me-1"> <%= task.status %> </span>
              <% elsif task.status.downcase == 'yet to start' %>
                <span class="badge bg-label-warning me-1"> <%= task.status %> </span>
              <% else %>
                <span class="badge bg-label-danger me-1"> <%= task.status %> </span>
              <% end %>
            </td>
            <td>
              <div class="dropdown is-small ">
                <div class="dropdown is-hoverable">
                  <div class="dropdown-trigger">
                    <button class="button is-small" aria-haspopup="true" aria-controls="dropdown-menu4">
                      <span class="icon is-small"> <i class="fas fa-angle-down" aria-hidden="true"></i> </span>
                    </button>
                  </div>
                  <div class="dropdown-menu is-small" id="dropdown-menu4" role="menu">
                    <div class="dropdown-content">
                      <div class="dropdown-item">
                        <%= link_to project_task_path(@project,task), class: "dropdown-item" do %>
                          <i class="bx bx-edit-alt me-1"></i> <span>Show</span>
                        <% end %>

                        <%= link_to edit_project_task_path(@project,task), class: "dropdown-item" do %>
                          <i class="bx bx-edit-alt me-1"></i> <span>Edit</span>
                        <% end %>

                      </div>
                    </div>
                  </div>
                </div>
            </div>
          </td>
          <td>
            <%= link_to "Delete",project_task_path(@project,task), method: :delete, data: { confirm: 'Are you sure?' }%>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to "Analytics", analytics_path(@project),class:"btn" %>


  <script>
    $('.notify_developers').on('click', function(){
        console.log('Email Action Triggered')
        $.ajax({
            type: "GET",
            url: 'http://localhost:3000/notify_users',
            data: { project_id: <%= @project.id %>},
            success: function(data){
                alert('Email sent successfully');
            },
            error: function(data, err){
                alert('Error occured');
            }
        })
    })
  </script>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

<%#= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/show.html.erb
<div class="container is-max-desktop" style="margin-top: 2rem">

  <article class="message is-info">
    <div class="message-header">
      <%= @task.title %> | <%= @task.project.title %>
      <span>
      <%= @task.status %>
    </span>
      <%= link_to('', project_tasks_path(@project), class: "delete") %>
    </div>
    <div class="message-body">
      <%= @task.description %>
    </div>
  </article>

</div>