config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :posts do
      get 'user_profile'
    end
  end
  resources :projects do
    resources :tasks
  end
  resources :teams
  devise_for :users

  root 'home#index'

  get "/join/:id", to:"teams#user" ,as:"join"
  get "/view/:id", to:"teams#view_team", as:"view_team"
  delete "/exit/:id", to:"teams#team_exit", as:"exit_team"
  get "/analytics/:id", to:"home#analytics" ,as:"analytics"
  get "/notify_users", to: "tasks#notify_developers", as:"notify_developers"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @teams = Team.all
  end
  def analytics
    @project = Project.find(params[:id])

    @yet_to_start = @project.tasks.where(:status=>"YET TO START")
    @in_progress = @project.tasks.where(:status=>"IN PROGRESS")
    @completed = @project.tasks.where(:status=>"COMPLETED")

    @task_with_one_hours = @project.tasks.where(:Estimation=>"1")
    @task_with_two_hours = @project.tasks.where(:Estimation=>"2")
    @task_with_three_hours = @project.tasks.where(:Estimation=>"3")
    @task_with_four_hours = @project.tasks.where(:Estimation=>"4")
    @task_with_five_hours = @project.tasks.where(:Estimation=>"5")

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/analytics.html.erb
<div class="columns">
  <div class="column">
    <canvas id="myChart" style="width:100%;max-width:600px"></canvas>
  </div>

  <div class="column">
    <canvas id="pieChart" style="width:100%;max-width:600px"></canvas>
  </div>
</div>

<script>
    const xValues = ["In-Progress", "Yet to Start", "Completed"];
    const yValues = [<%= @in_progress.count %>,<%= @yet_to_start.count %>,<%= @completed.count %>];
    var barColors = [
        "#b91d47",
        "#00aba9",
        "#2b5797",
    ];

    new Chart("pieChart", {
        type: "pie",
        data: {
            labels: xValues,
            datasets: [{
                backgroundColor: barColors,
                data: yValues
            }]
        },
        options: {
            title: {
                display: true,
                text: "Task Progress"
            }
        }
    });

    const xValuess = ["1hrs","2hrs","3hrs","4hrs","5hrs"];
    const yValuess = [<%= @task_with_one_hours.count %>,<%= @task_with_two_hours.count %>,<%= @task_with_three_hours.count %>,<%= @task_with_four_hours.count %>,<%= @task_with_five_hours.count %>];

    console.log("Hello")
    console.log(yValuess)

    new Chart("myChart", {
        type: "line",
        data: {
            labels: xValuess,
            datasets: [{
                fill: false,
                lineTension: 0,
                backgroundColor: "rgba(0,0,255,1.0)",
                borderColor: "rgba(0,0,255,0.1)",
                data: yValuess
            }]
        },
        options: {
            legend: {display: false},
            scales: {
                yAxes: [{ticks: {min: 0, max: 20}}],
            },
            title: {
                display: true,
                text: "Task Estimation (in hours)"
            }
        }
    });

</script>

app/views/home/index.html.erb
<%#if user_signed_in? %>
<!--  <div class="container is-fluid" style="margin-top: 3rem;">-->
<!--    <div class="columns is-multiline" style="justify-content: center; align-items: center;">-->
      <%#= button_to("Create Team", new_team_path, class: "button", method: :get, style: "width: 15rem; background-color: #8080ff") %>
<!--    </div>-->
    <%# if @teams.count == 0 %>
      <%#=link_to "Create a team",new_team_path, class: "card-footer-item" %>
    <%# else %>
<!--      <div class="columns is-multiline" style="justify-content: center; align-items: center;">-->
          <%# @teams.each do |team| %>
<!--            <div class="column is-one-quarter" style="width: 25rem">-->
<!--              <div class="card">-->
<!--                <header class="card-header">-->
<!--                  <p class="card-header-title">-->
<!--                    <%#=team.name %><br>-->
<!--                  </p>-->
<!--                </header>-->
<!--                <div class="card-content">-->
<!--                  <div class="content">-->
                    <%#= team.description %>
<!--                    <br>-->
<!--                  </div>-->
<!--                </div>-->
<!--                <footer class="card-footer">-->
                  <%#= link_to("Show", team_path(team), class: "card-footer-item redirect-link") %>
                  <%#= link_to("Edit", edit_team_path(team), class: "card-footer-item redirect-link") %>
<!--                </footer>-->
<!--              </div>-->
<!--            </div>-->
          <%# end %>
<!--        </div>-->

    <%# end %>
<!--  </div>-->
<%# else %>
<%# end %>

<%= render 'layouts/home' %>
<%= render('layouts/partials/footer') %>