config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :posts do
      get 'user_profile'
    end
  end
  resources :projects do
    resources :tasks
  end
  resources :teams
  devise_for :users

  root 'home#index'

  get "/join/:id", to:"teams#user" ,as:"join"
  get "/view/:id", to:"teams#view_team", as:"view_team"
  delete "/exit/:id", to:"teams#team_exit", as:"exit_team"
  get "/analytics/:id", to:"home#analytics" ,as:"analytics"
  get "/notify_users", to: "tasks#notify_developers", as:"notify_developers"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_rich_text :description

  # ====== Validations ======
  validates :description, presence: true
  validates :title, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<script>
    $(document).ready(function(){
        const parent = document.querySelector("#form")
        const notification = document.querySelector(".notify")
        if(parent.contains(notification)){
            if(notification.contains(document.querySelector(".team-name")) && notification.contains(document.querySelector(".team-description"))){
                $('.name-message').append("<p class='notification is-danger'>Title can't be blank</p>")
                $('.description-message').append("<p class='notification is-danger'>Description can't be blank</p>")
            }
            else if(notification.contains(document.querySelector(".team-description"))){
                console.log("Description can't be blank")
                $('.description-message').append("<p class='notification is-danger'>Description can't be blank</p>")
            }
            else{
                console.log("Name and Description are blank")
                $('.name-message').append("<p class='notification is-danger'>Title can't be blank</p>")
                $('.description-message').append("<p class='notification is-danger'>Description can't be blank</p>")
            }
        }
    })
</script>

<div id="form">
  <%= form_with(model: project) do |form| %>
    <% if project.errors.any? %>
      <div class="notify" style="text-align: center;">
<!--        <h2><%#= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>-->
        <ul>
          <% project.errors.each do |error| %>
              <% if error.full_message == "Title can't be blank" %>
                <div class="team-name"></div>
              <% elsif error.full_message == "Title can't be blank Description can't be blank" %>
                <div class="full-message"></div>
              <% else %>
                <div class="team-description"></div>
              <% end %>
          <% end %>
        </ul>
      </div>
      </div>
    <% end %>

    <div class="field">
      <label class="label">Project Name</label>
      <span class="name-message"></span>
      <%= form.text_field :title, class: "input" %>
    </div>

    <div class="field">
      <label class="label">Description</label>
      <span class="description-message"></span>
      <%= form.rich_text_area :description, class: "" %>
    </div>

    <div class="actions columns">
      <div class="column">
        <%= form.submit :submit, class: "button is-link" %>
      </div>
      <div class="column">
        <%= link_to 'Back', root_path, class: "button is-light redirect-link" %>
      </div>
    </div>
  <% end %>

</div>

app/views/projects/edit.html.erb
<div class="container" style="height: 35rem; margin-top: 5rem;">
  <%= render 'form', project: @project %>
</div>

app/views/projects/index.html.erb
<br/>
<div class="container is-max-desktop content" style="height: 35rem;">
  <%= render("layouts/partials/project_table", projects: @projects) %>
</div>

app/views/projects/new.html.erb
<div class="container is-max-desktop content">
  <h3 style="text-align: center">New Team</h3>
  <%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<div class="container" style="width: 50rem;">
  <section class="section">
    <div class="container">
      <div class="columns">
        <div class="column">
          <div class="card", style="width: 35rem">
            <div class="card-content p-0 is-flex is-flex-direction-column">
              <div class="content p-5 has-text-grey-light">
                <h3><%= link_to @project.title, edit_project_path(@project) %></h3>
                <p class="is-size-6 has-text-weight-normal"> <%= @project.description %> </p>
              </div>
              <div class="content p-5 has-background-info-light">
                <div class="columns">
                  <div class="column">
                    <div class="is-size-6">
                      <span class="has-text-weight-semibold">Since: </span><%= @project.created_at.strftime("%d-%m-%Y") %>
                    </div>
                    <div class="is-size-6">
                      <span class="has-text-primary-dark">Tasks count: </span> <%=@project.tasks.count %>
                    </div>

                  </div>
                  <div class="column">
                    <%= link_to 'Show Tasks', project_tasks_path(@project), class: "button is-primary is-medium is-fullwidth has-text-weight-semibold" %>
                  </div>
                </div>
                <p class="is-size-7"></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>