config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :posts do
      get 'user_profile'
    end
  end
  resources :projects do
    resources :tasks
  end
  resources :teams
  devise_for :users

  root 'home#index'

  get "/join/:id", to:"teams#user" ,as:"join"
  get "/view/:id", to:"teams#view_team", as:"view_team"
  delete "/exit/:id", to:"teams#team_exit", as:"exit_team"
  get "/analytics/:id", to:"home#analytics" ,as:"analytics"
  get "/notify_users", to: "tasks#notify_developers", as:"notify_developers"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/_contact_footer.html.erb
<div class="Layout-module--bottomOuter--c4fa1">
  <div class="Layout-module--blueDiagonal--2ee7f"></div>
  <div class="Layout-module--bottom--c6f94">
    <div class="getStartedWithDolt__container">
      <div class="getStartedWithDolt__overflowContainer">
        <div class="getStartedWithDolt__aura">
          <div class="getStartedWithDolt__blueAura"></div>
        </div>
        <div class="getStartedWithDolt__aura">
          <div class="getStartedWithDolt__greenAura"></div>
        </div>
        <div class="getStartedWithDolt__content">
          <div class="getStartedWithDolt__top">
            <a class="getStartedWithDolt__textLink" href="https://github.com/dolthub/dolt" target="_blank" rel="noopener noreferrer">
              <span class="getStartedWithDolt__openSourceText"> </span>
            </a>
          </div>
          <div class="getStartedWithDolt__bottom">
            <div>
              <div class="getStartedWithDolt__dataEvolution">JOIN THE DATA EVOLUTION</div>
              <h1 class="getStartedWithDolt__titleForDarkBg">Get started with Dolt</h1>
              <div class="getStartedWithDolt__bottomButtons">
                <button class="button bg-button-1 getStartedWithDolt__installDoltButton" type="button">Create an account</button>
                <button class="" type="button"></button>
              </div>
            </div>
          </div>
          <div class="mailing-list" aria-label="mailing-list">
            <p class="mailing-list__header">Register your email to receive latest update</p>
            <form data-cy="mailing-list-form">
              <div class="mailing-list__form">
                <input type="email" placeholder="your email address" data-cy="mailchimp-input" class="mailing-list__form-input"/>
                <button type="submit" data-cy="mailchimp-submit-button" disabled="">Submit</button>
              </div>
              <div class="mailing-list__message" data-testid="submitting-message"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <footer class="site-footer site-footer--transparentBg Layout-module--footer--ef4f9" data-cy="site-footer" aria-label="site-footer">
      <div class="site-footer__container">
        <div class="site-footer__logo-and-links">
          <div class="site-footer__logo-links">
            <div class="site-footer__dolthub-logo">
              <div class="">
                <div class="">
                </div>
              </div>
            </div>
          </div>
          <div class="site-footer__text-links">
            <div class="site-footer__dolthub-links" data-cy="footer-links">
              <ul>
                <li>
                  <a href="https://docs.dolthub.com" data-cy="footer-about-dolt">About Dolt</a>
                </li>
                <li>
                  <a href="https://www.dolthub.com/pricing" data-cy="footer-pricing">Pricing</a>
                </li>
                <li>
                  <a href="https://docs.dolthub.com" data-cy="footer-documentation">Documentation</a>
                </li>
                <li>
                  <a href="https://www.dolthub.com/blog" data-cy="footer-blog">Blog</a>
                </li>
                <li>
                  <a href="https://www.dolthub.com/team" data-cy="footer-team">Team</a>
                </li>
              </ul>
            </div>
            <div class="site-footer__fine-print-links" data-cy="footer-social-links">
              <ul>
                <li>
                  <a href="https://www.dolthub.com/privacy-policy" data-cy="footer-privacy-policy">Privacy</a>
                </li>
                <li>
                  <a href="https://www.dolthub.com/terms" data-cy="footer-terms-of-service">Terms</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="site-footer__social" data-cy="footer-social-links">
          <a class="site-footer__social__link" href="https://github.com/dolthub/dolt" aria-label="GitHub" target="_blank" rel="noopener noreferrer">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 496 512" class="site-footer__social__icon" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
              <path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path>
            </svg>
          </a>
          <a class="site-footer__social__link" href="https://discord.gg/gqr7K4VNKe" aria-label="Discord" target="_blank" rel="noopener noreferrer">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 448 512" class="site-footer__social__icon" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
              <path d="M297.216 243.2c0 15.616-11.52 28.416-26.112 28.416-14.336 0-26.112-12.8-26.112-28.416s11.52-28.416 26.112-28.416c14.592 0 26.112 12.8 26.112 28.416zm-119.552-28.416c-14.592 0-26.112 12.8-26.112 28.416s11.776 28.416 26.112 28.416c14.592 0 26.112-12.8 26.112-28.416.256-15.616-11.52-28.416-26.112-28.416zM448 52.736V512c-64.494-56.994-43.868-38.128-118.784-107.776l13.568 47.36H52.48C23.552 451.584 0 428.032 0 398.848V52.736C0 23.552 23.552 0 52.48 0h343.04C424.448 0 448 23.552 448 52.736zm-72.96 242.688c0-82.432-36.864-149.248-36.864-149.248-36.864-27.648-71.936-26.88-71.936-26.88l-3.584 4.096c43.52 13.312 63.744 32.512 63.744 32.512-60.811-33.329-132.244-33.335-191.232-7.424-9.472 4.352-15.104 7.424-15.104 7.424s21.248-20.224 67.328-33.536l-2.56-3.072s-35.072-.768-71.936 26.88c0 0-36.864 66.816-36.864 149.248 0 0 21.504 37.12 78.08 38.912 0 0 9.472-11.52 17.152-21.248-32.512-9.728-44.8-30.208-44.8-30.208 3.766 2.636 9.976 6.053 10.496 6.4 43.21 24.198 104.588 32.126 159.744 8.96 8.96-3.328 18.944-8.192 29.44-15.104 0 0-12.8 20.992-46.336 30.464 7.68 9.728 16.896 20.736 16.896 20.736 56.576-1.792 78.336-38.912 78.336-38.912z"></path>
            </svg>
          </a>
          <a class="site-footer__social__link" href="https://www.linkedin.com/company/dolthubinc/" aria-label="Linkedin" target="_blank" rel="noopener noreferrer">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 448 512" class="site-footer__social__icon" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
              <path d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z"></path>
            </svg>
          </a>
          <a class="site-footer__social__link" href="https://www.twitter.com/dolthub" aria-label="Twitter" target="_blank" rel="noopener noreferrer">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" class="site-footer__social__icon" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
              <path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path>
            </svg>
          </a>
        </div>
      </div>
      <div class="site-footer__copyright" aria-label="copyright">
        © <!-- -->2023<!-- --> SaaSApp, Inc. All rights reserved.
      </div>
    </footer>
  </div>
</div>
</div></div>
<div id="gatsby-announcer" style="position:absolute;top:0;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0, 0, 0, 0);white-space:nowrap;border:0" aria-live="assertive" aria-atomic="true"></div>
</div>

app/views/layouts/partials/_footer.html.erb
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->

<!--<head>-->
<!--  <meta charset="UTF-8">-->
<!--  <meta http-equiv="X-UA-Compatible" content="IE=edge">-->
<!--  <meta name="viewport" content="width=device-width, initial-scale=1">-->
<!--  <link rel="shortcut icon" href="../images/fav_icon.png" type="image/x-icon">-->
<!-- Bulma Version 0.9.0-->
<!--  <link rel="stylesheet" href="https://unpkg.com/bulma@0.9.0/css/bulma.min.css" />-->
<!--  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"-->
<!--        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">-->
<!--  <link rel="stylesheet" href="../css/contact.css">-->
<!--</head>-->

<!--<body>-->
<!-- START NAV -->
<!-- END NAV -->
<section class="hero is-fullheight">
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="columns is-8 is-variable ">
        <div class="column is-two-thirds has-text-left">
          <h1 class="title is-1">Contact Us</h1>
          <p class="is-size-6"></p>
          <br>
          <div class="social-media">
            <a href="https://facebook.com" target="_blank" class="button is-light"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
            <a href="https://instagram.com" target="_blank" class="button is-light"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a href="https://twitter.com" target="_blank" class="button is-light"><i class="fa fa-twitter" aria-hidden="true"></i></a>
          </div>
        </div>
        <div class="column is-one-third has-text-left">
          <div class="field">
            <label class="label">Email</label>
            <div class="control">
              <input class="input is-medium" type="text">
            </div>
          </div>
          <div class="field">
            <label class="label">Message</label>
            <div class="control">
              <textarea class="textarea is-small"></textarea>
            </div>
          </div>
          <div class="control">
            <button type="submit" class="button is-link is-fullwidth has-text-weight-medium is-medium">Send Mail</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!--</body>-->

<!--</html>-->

app/views/layouts/partials/_home_nav.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <% link_to root_path %>
      <img src="https://images-platform.99static.com/M0DjlvDlhr8r1g36F_IJHR0eCRQ=/500x500/top/smart/99designs-contests-attachments/41/41565/attachment_41565366" width="58" height="20"/>
  </div>

  <div class="navbar-menu">
    <%= link_to "Home",root_path,class:" partials-item", style: "font-size:18px", class: "navbar-item" %>
    <%= link_to "Teams",teams_path,class:" partials-item", style: "font-size:18px", class: "navbar-item" %>
    <%= link_to "Projects",projects_path,class:" partials-item", style: "font-size:18px", class: "navbar-item" %>
    <div class="navbar-end">
      <%= link_to "Blog",topics_path,class:" partials-item", style: "font-size:18px", class: "navbar-item" %>

      <div class="navbar-item">
        <% if user_signed_in? %>
          <h3><span>Welcome <%= link_to(current_user.email, edit_user_registration_path, class: "redirect-link") %></span></h3>&nbsp; |&nbsp;
          <%= link_to("Log out", destroy_user_session_path, class: "button is-light is-small", method: :delete ) %>
        <% else %>
          <%= link_to("Sign up", new_user_registration_path, class: "button is-primary", class: 'button is-success') %>
          <%= button_to("Log in", user_session_path, class: "button is-light") %>
        <% end %>
      </div>

    </div>
  </div>
</nav>

app/views/layouts/partials/_project_table.html.erb
<div class="card" style="margin-top: 3rem;">
  <div class="columns is-multiline" style="justify-content: center; align-items: center;">
    <%= button_to("New Project", new_project_path, class: "button", method: :get, style: "width: 15rem; background-color: #8080ff") %>
  </div>
  <div class="table-responsive text-nowrap" style="height: 25rem; justify-content: center;">
    <table class="table" style="text-align: left;">
      <thead class="table-light">
      <tr>
        <th>Title</th>
        <th>Client</th>
        <th>Lead</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        <% projects.each do |project| %>
          <tr style="justify-content: center;" >
            <td><strong> <%= project.title %> </strong></td>
            <td>Albert Cook</td>
            <td>
              <ul class="list-unstyled users-list m-0 avatar-group d-flex align-items-center" style="list-style: none;">
                <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" class="avatar avatar-xs pull-up" title="Naveen">
                  <img src="../assets/img/avatars/5.png" alt="Avatar" class="rounded-circle" />
                </li>
                <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" class="avatar avatar-xs pull-up" title="Vennkat">
                  <img src="../assets/img/avatars/7.png" alt="Avatar" class="rounded-circle" />
                </li>
                <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" class="avatar avatar-xs pull-up" title="Ram">
                  <img src="../assets/img/avatars/5.png" alt="Avatar" class="rounded-circle" />
                </li>
                <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" class="avatar avatar-xs pull-up" title="Vaithi" >
                  <img src="../assets/img/avatars/7.png" alt="Avatar" class="rounded-circle" />
                </li>
              </ul>
            </td>
            <td><span class="badge bg-label-primary me-1">Active</span></td>
            <td>
              <div class="dropdown is-small ">
                <div class="dropdown is-hoverable">
                  <div class="dropdown-trigger">
                    <button class="button is-small" aria-haspopup="true" aria-controls="dropdown-menu4">
                      <span class="icon is-small"> <i class="fas fa-angle-down" aria-hidden="true"></i> </span>
                    </button>
                  </div>
                  <div class="dropdown-menu is-small" id="dropdown-menu4" role="menu">
                    <div class="dropdown-content">
                      <div class="dropdown-item">
                        <%= link_to project, class: "dropdown-item" do %>
                          <i class="bx bx-edit-alt me-1"></i> <span>Show</span>
                        <% end %>

                        <%= link_to edit_project_path(project), class: "dropdown-item" do %>
                          <i class="bx bx-edit-alt me-1"></i> <span>Edit</span>
                        <% end %>

                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/partials/_search.html.erb
<div class="navbar-nav align-items-center">
  <div class="nav-item d-flex align-items-center">
    <i class="bx bx-search fs-4 lh-0"></i>
    <input
      type="text"
      class="form-control border-0 shadow-none"
      placeholder="Search..."
      aria-label="Search..."
      />
  </div>
</div>